
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND APAGAR ASSIGN BOTON CADENA CARACTER COLA COLON COMMA COMPONENTE CONFIGURAR CONFIGURAR_PIN DISPLAY DIVIDE DOT EN ENCENDER ENTERO EQ ESCRIBIR_DIGITAL FALSE FUNCION GE GIRAR GT HACER ID IMPRIMIR INFINITA LBRACE LBRACKET LE LED LEER LEER_ANALOGICO LEER_DIGITAL LEER_TEXTO LIBRERIA LISTA LLAMAR LPAREN LT MICROPROCESADOR MIENTRAS MINUS MINUS_ASSIGN MOD NE NOT OR PARA PILA PIN_ANALOGICO PIN_DIGITAL PLUS PLUS_ASSIGN POW RBRACE RBRACKET REAL RPAREN SEMI SENSOR SERVOMOTOR SI SINO TERMOMETRO TIMES TIPO_BOOLEAN TIPO_CHAR TIPO_DOUBLE TIPO_INT TIPO_STRING TRUE VENTILADORprograma : declaraciones\ndeclaraciones : declaracion declaraciones\n              | empty\n\ndeclaracion : decl_componente\n            | decl_funcion\n            | stmt_simple\n\ntipo : ID\n     | LED\n     | SENSOR\n     | TERMOMETRO\n     | SERVOMOTOR\n     | VENTILADOR\n     | MICROPROCESADOR\n     | DISPLAY\n     | BOTON\ndecl_componente : COMPONENTE ID ASSIGN tipo SEMI\ndecl_funcion : FUNCION ID LPAREN lista_ids RPAREN LBRACE declaraciones RBRACE\n\nlista_ids : ID coma_ids\n          | empty\n\ncoma_ids : COMMA ID coma_ids\n         | empty\n\nstmt_simple : ENCENDER ID SEMI\n            | APAGAR ID SEMI\n            | LEER ID SEMI\n            | GIRAR ID ID SEMI\n            | ID LPAREN lista_ids RPAREN SEMI\nempty :'
    
_lr_action_items = {'$end':([0,1,2,3,4,5,6,7,15,28,29,30,47,48,50,55,],[-27,0,-1,-27,-3,-4,-5,-6,-2,-22,-23,-24,-25,-16,-26,-17,]),'COMPONENTE':([0,3,5,6,7,28,29,30,47,48,50,53,55,],[8,8,-4,-5,-6,-22,-23,-24,-25,-16,-26,8,-17,]),'FUNCION':([0,3,5,6,7,28,29,30,47,48,50,53,55,],[10,10,-4,-5,-6,-22,-23,-24,-25,-16,-26,10,-17,]),'ENCENDER':([0,3,5,6,7,28,29,30,47,48,50,53,55,],[11,11,-4,-5,-6,-22,-23,-24,-25,-16,-26,11,-17,]),'APAGAR':([0,3,5,6,7,28,29,30,47,48,50,53,55,],[12,12,-4,-5,-6,-22,-23,-24,-25,-16,-26,12,-17,]),'LEER':([0,3,5,6,7,28,29,30,47,48,50,53,55,],[13,13,-4,-5,-6,-22,-23,-24,-25,-16,-26,13,-17,]),'GIRAR':([0,3,5,6,7,28,29,30,47,48,50,53,55,],[14,14,-4,-5,-6,-22,-23,-24,-25,-16,-26,14,-17,]),'ID':([0,3,5,6,7,8,10,11,12,13,14,17,22,23,27,28,29,30,43,47,48,50,53,55,],[9,9,-4,-5,-6,16,18,19,20,21,22,24,31,32,24,-22,-23,-24,49,-25,-16,-26,9,-17,]),'RBRACE':([3,4,5,6,7,15,28,29,30,47,48,50,53,54,55,],[-27,-3,-4,-5,-6,-2,-22,-23,-24,-25,-16,-26,-27,55,-17,]),'LPAREN':([9,18,],[17,27,]),'ASSIGN':([16,],[23,]),'RPAREN':([17,24,25,26,27,42,44,46,49,52,],[-27,-27,45,-19,-27,-18,-21,51,-27,-20,]),'SEMI':([19,20,21,31,32,33,34,35,36,37,38,39,40,41,45,],[28,29,30,47,-7,48,-8,-9,-10,-11,-12,-13,-14,-15,50,]),'LED':([23,],[34,]),'SENSOR':([23,],[35,]),'TERMOMETRO':([23,],[36,]),'SERVOMOTOR':([23,],[37,]),'VENTILADOR':([23,],[38,]),'MICROPROCESADOR':([23,],[39,]),'DISPLAY':([23,],[40,]),'BOTON':([23,],[41,]),'COMMA':([24,49,],[43,43,]),'LBRACE':([51,],[53,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'declaraciones':([0,3,53,],[2,15,54,]),'declaracion':([0,3,53,],[3,3,3,]),'empty':([0,3,17,24,27,49,53,],[4,4,26,44,26,44,4,]),'decl_componente':([0,3,53,],[5,5,5,]),'decl_funcion':([0,3,53,],[6,6,6,]),'stmt_simple':([0,3,53,],[7,7,7,]),'lista_ids':([17,27,],[25,46,]),'tipo':([23,],[33,]),'coma_ids':([24,49,],[42,52,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> declaraciones','programa',1,'p_programa','parser.py',19),
  ('declaraciones -> declaracion declaraciones','declaraciones',2,'p_declaraciones','parser.py',25),
  ('declaraciones -> empty','declaraciones',1,'p_declaraciones','parser.py',26),
  ('declaracion -> decl_componente','declaracion',1,'p_declaracion','parser.py',36),
  ('declaracion -> decl_funcion','declaracion',1,'p_declaracion','parser.py',37),
  ('declaracion -> stmt_simple','declaracion',1,'p_declaracion','parser.py',38),
  ('tipo -> ID','tipo',1,'p_tipo','parser.py',44),
  ('tipo -> LED','tipo',1,'p_tipo','parser.py',45),
  ('tipo -> SENSOR','tipo',1,'p_tipo','parser.py',46),
  ('tipo -> TERMOMETRO','tipo',1,'p_tipo','parser.py',47),
  ('tipo -> SERVOMOTOR','tipo',1,'p_tipo','parser.py',48),
  ('tipo -> VENTILADOR','tipo',1,'p_tipo','parser.py',49),
  ('tipo -> MICROPROCESADOR','tipo',1,'p_tipo','parser.py',50),
  ('tipo -> DISPLAY','tipo',1,'p_tipo','parser.py',51),
  ('tipo -> BOTON','tipo',1,'p_tipo','parser.py',52),
  ('decl_componente -> COMPONENTE ID ASSIGN tipo SEMI','decl_componente',5,'p_decl_componente','parser.py',57),
  ('decl_funcion -> FUNCION ID LPAREN lista_ids RPAREN LBRACE declaraciones RBRACE','decl_funcion',8,'p_decl_funcion','parser.py',63),
  ('lista_ids -> ID coma_ids','lista_ids',2,'p_lista_ids','parser.py',70),
  ('lista_ids -> empty','lista_ids',1,'p_lista_ids','parser.py',71),
  ('coma_ids -> COMMA ID coma_ids','coma_ids',3,'p_coma_ids','parser.py',80),
  ('coma_ids -> empty','coma_ids',1,'p_coma_ids','parser.py',81),
  ('stmt_simple -> ENCENDER ID SEMI','stmt_simple',3,'p_stmt_simple','parser.py',91),
  ('stmt_simple -> APAGAR ID SEMI','stmt_simple',3,'p_stmt_simple','parser.py',92),
  ('stmt_simple -> LEER ID SEMI','stmt_simple',3,'p_stmt_simple','parser.py',93),
  ('stmt_simple -> GIRAR ID ID SEMI','stmt_simple',4,'p_stmt_simple','parser.py',94),
  ('stmt_simple -> ID LPAREN lista_ids RPAREN SEMI','stmt_simple',5,'p_stmt_simple','parser.py',95),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',105),
]
